import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import About from "../components/About";
import Contact from "../components/Contact";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import WorkExperience from "../components/WorkExperience";

const Home: NextPage = () => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 xl:items-center scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#f7ab0a]/80">
      <Head>
        <title>Hrithik.s.Raj</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />

        <section id="hero" className="snap-start">
          <Hero />
        </section>

        <section id="about" className="snap-center">
          <About />
        </section>

        <section id="experience" className="snap-center">
          <WorkExperience />
        </section>

        <section id="skills" className="snap-start">
          <Skills />
        </section>

        <section id="projects" className="snap-start">
          <Projects />
        </section>

        <section id="contact" className="snap-start">
          <Contact />
        </section>

        <Link href="#hero">
          <footer className="sticky bottom-5 w-full cursor-pointer ">
            <div className="flex items-center justify-center group">
              <img
                className="w-10 h-10 rounded-full filter grayscale group-hover:grayscale-0 "
                src="https://i.ibb.co/HKrwYqS/up-arrow-1.png"
                alt=""
              />
              <h5 className="opacity-0 group-hover:opacity-100 text-xs justify-center flex text-white">
                {" "}
                Top
              </h5>
            </div>
          </footer>
        </Link>
      </div>
    </div>
  );
};

export default Home;
